RELAY_ENVELOPE_CONTROL = "control"
RELAY_ENVELOPE_DATA = "data"

RELAY_ACTION_REGISTER = "register"
RELAY_ACTION_REGISTERED = "registered"
RELAY_ACTION_PEER_CONNECTED = "peer_connected"
RELAY_ACTION_PEER_DISCONNECTED = "peer_disconnected"
RELAY_ACTION_ERROR = "error"
RELAY_ACTION_CLOCK_SYNC_PING = "clock_sync_ping"
RELAY_ACTION_CLOCK_SYNC_ACK = "clock_sync_ack"
RELAY_ACTION_CLOCK_SYNC_PUBLISH = "clock_sync_publish"
RELAY_ACTION_FULL_CHAIN_TIME_SYNC_REQUEST = "full_chain_time_sync_request"
RELAY_ACTION_FULL_CHAIN_TIME_SYNC_RESULT = "full_chain_time_sync_result"

RELAY_ROLE_MASTER = "master"
RELAY_ROLE_SLAVE = "slave"

STREAM_CLOSED_INTERNAL_TYPE = "_stream_closed"
