RELAY_ENVELOPE_CONTROL = "control"
RELAY_ENVELOPE_DATA = "data"

RELAY_ACTION_REGISTER = "register"
RELAY_ACTION_REGISTERED = "registered"
RELAY_ACTION_PEER_CONNECTED = "peer_connected"
RELAY_ACTION_PEER_DISCONNECTED = "peer_disconnected"
RELAY_ACTION_ERROR = "error"

RELAY_ROLE_MASTER = "master"
RELAY_ROLE_SLAVE = "slave"

STREAM_CLOSED_INTERNAL_TYPE = "_stream_closed"
